alias bashaliases='vi ~/.bash_aliases'
alias fuck='sudo !!'
alias g='grep -I --exclude={tags,.git}'
alias journal='vi ~/vmshared/journal/$(date +%F.txt)'
alias profile='vi ~/dotfiles/profile-appendix; source ~/.profile'
alias tgrep='grep -I --exclude={tags,.git}'
alias vimrc='vi ~/.vimrc'
alias vit='vi -t'
alias up='cd'
alias wd='cd'
