#!/usr/bin/env python3
# This is not actually xclip, but a makeshift subsitute for WSL
import sys
import subprocess

def copy(text):
    p = subprocess.Popen(['clip.exe'],
            stdin=subprocess.PIPE, close_fds=True)
    p.communicate(input=text.strip().encode("utf8"))

def paste():
    p = subprocess.Popen(['powershell.exe', '-command', 'Get-Clipboard'],
                         stdout=subprocess.PIPE, close_fds=True)
    print(p.stdout.read().decode("utf8"))

if __name__ == "__main__":
    paste()
    # copy(sys.stdin.read())
