[project]
name = # Required, fill it yourself.
version = # Required, fill it yourself.
description = "I clearly did not configure a description for this. Whoops."
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
keywords = []
authors = [] # Example: {name = "Sombra", email = "sombra@talon.com"}
maintainers = # Same format as above
dependencies = [] # Examples: ["httpx", "django>2.1; os_name != 'nt'"]

[project.optional-dependencies]
gui = [] # Example: ["PyQt5"]
cli = [] # Example: ["click"]

[project.urls]
Homepage = "https://127.0.0.1"
Documentation = "https://127.0.0.1"
Repository = "https://127.0.0.1/PROJECT_PLACEHOLDER.git"
Changelog = "https://127.0.0.1/CHANGELOG.md"

[project.scripts]
cli = "PROJECT_PLACEHOLDER:main_cli"
gui = "PROJECT_PLACEHOLDER:main_gui"

[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"
