#!/usr/bin/env python3
import subprocess

def main():
    command_args = ["git", "grep", "-inor", r"# \?TODO.*"]
    p = subprocess.run(
        command_args,
        stdout=subprocess.PIPE,
        universal_newlines=True
    )
    print(p.stdout.strip())

if __name__ == "__main__":
    main()
