#!/usr/bin/env python3
import argparse
import subprocess
import pathlib

def _get_remotes():
    output = subprocess.check_output(
        ("git", "remote", "show"),
        universal_newlines=True
    )
    for line in output.splitlines():
        yield line


def remote_to_url(remote_name):
    output = subprocess.check_output(
        ("git", "remote", "get-url", remote_name),
        universal_newlines=True
    )
    url = output.strip()
    return url

def _create_bundle(bundle_path):
    command = ("git", "bundle", "create", bundle_path, "--all")
    output = subprocess.check_output(command, universal_newlines=True)
    print(output)


def get_arg_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "remote",
        type=pathlib.Path
    )
    return parser


def main():
    parser = get_arg_parser()
    args = parser.parse_args()
    bundle_path = remote_to_url(args.remote)
    _create_bundle(args.bundle_path)


if __name__ == "__main__":
    main()

